version: '3.8'

services:
  port-sync:
    build: .
    container_name: port-sync
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app_network
    volumes:
      - ./config.toml:/app/config.toml
      - ./data:/app/data
    deploy:
      resources:
        limits:
          memory: 200m

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app_network
    command: ["redis-server", "--appendonly", "no"]
    deploy:
      resources:
        limits:
          memory: 500m
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  app_network:
    driver: bridge
